#!/bin/sh
. ~/.dotfiles/misc/.env # load the $CONF variable
. misc/m4

user=$(whoami)

if [ $CONF = "server" ]
then
   if [ -s server-key ]
   then
      key=$(cat server-key)
   else
      key=$(dialog --title "Tailscale key" --backtitle "Enter your tailscale key" --inputbox " Enter your tailscale key" 8 60 tskey- 2>&1 >/dev/tty)
   fi
echo $key > server-key
else
   if [ -s key ]
   then
      key="$(cat key)" # run the command to get host-id locally
   else
      key=$(dialog --title "Tailscale key" --backtitle "Enter your tailscale key" --inputbox " Enter your tailscale key" 8 60 tskey- 2>&1 >/dev/tty)
   fi
echo $key > key
fi
case $1 in
   "add") replace_system_file tskey_here "$key" key
   ;;
   *) exit 0
   ;;
esac
