#!/bin/sh
. ~/.dotfiles/misc/.env # load the $CONF variable

user=$(whoami)
#cmd="cat /home/$user/.dotfiles/key" # command to get host-id
ip="$(tailscale ip -4 server)" # get servers ip (only working iwth setup tailscale)
if [ $CONF = "server" ]
then
   #ssh "$ip" "$cmd" # get host id over ssh (into server)
   if [ -e server-key ]
   then
      key=$(cat server-key)
   else
      key=$(dialog --title "Tailscale key" --backtitle "Enter your tailscale key" --inputbox " Enter your tailscale key" 8 60 tskey- 2>&1 >/dev/tty)
   fi
echo $key > server-key
else
   if [ -e key ]
   then
      key="$(cat key)" # run the command to get host-id locally
   else
      key=$(dialog --title "Tailscale key" --backtitle "Enter your tailscale key" --inputbox " Enter your tailscale key" 8 60 tskey- 2>&1 >/dev/tty)
   fi
echo $key > key
fi
case $1 in
   "add") sed -i "s/tskey-examplekeyhere/$key/g" system/key.nix 
   ;;
   "rm") sed -i "s/$key/tskey-examplekeyhere/g" system/key.nix 
   ;;
   *) exit 0
   ;;
esac
