#!/bin/sh
. ~/.dotfiles/misc/.env # load the $CONF variable
user=$(whoami)
cmd="cat /home/$user/.dotfiles/key" # command to get host-id
ip="$(tailscale ip -4 server)" # get servers ip (only working iwth setup tailscale)
if [ $CONF = "server" ]
then
   ssh "$ip" "$cmd" # get host id over ssh (into server)
else
   if [ -e key ]
   then
      $cmd # run the command to get host-id locally
   fi
   
fi
