#!/bin/sh
. ./misc/.env
replace_system_file(){
   # Usage
   # replace_system_file <to_replace> <replace_with> <filename>
   m4 -G -D$1="$2" system/$3.nix.template > system/$3.nix
}
export -f replace_system_file
