---
version: '3'

dotenv: ['misc/.env']

tasks:
  apply:
    cmds: 
      - task: hostid
      - task: tailscale
      - echo "applying $CONF ..."
      - ./misc/root nixos-rebuild --flake .#$CONF -p $CONF --install-bootloader switch
      - task: rm-hostid
      - task: rm-tailscale

  vm:
    cmds: 
      - task: hostid
      - echo "building VM of $CONF ..."
      - ./misc/root nixos-rebuild --flake .#$CONF -p $CONF build-vm
      - task: rm-hostid

  rm:
    cmds:
      - ./misc/root nix-collect-garbage --delete-older-than 14d

  hostid:
    cmds:
      - sed -i "s/12355671/$(./misc/host-id)/g" system/configuration.nix

  rm-hostid:
    cmds:
      - sed -i "s/$(./misc/host-id)/12355671/g" system/configuration.nix

  cp-hardware:
    cmds:
      - cp -f /etc/nixos/hardware-configuration.nix system

  auto-snapshot:
    cmds:
      - ./misc/root zfs set com.sun:auto-snapshot=true NIXROOT/home

  update:
    cmds:
      - nix flake update
  
  cupdate:
    cmds:
      - task: update
      - git add flake.lock
      - git commit -m "update flake.lock"

  test:
    cmds:
      - task: apply
      - nix flake check

  push:
    cmds:
      - task: test
      - git push


  apply-user:
    cmds:
      - nix build .#homeManagerConfigurations.$USER.activationPackage
      - ./result/activate

  tailscale:
    cmds:
      #- sed -i "s/#.\/system\/key.nix/.\/system\/key.nix/g" flake.nix
      - sed -i "s/tskey-examplekeyhere/$(./misc/get-key)/g" system/key.nix 


  rm-tailscale:
    cmds:
      - sed -i "s/$(./misc/get-key)/tskey-examplekeyhere/g" system/key.nix 

  jellyfin:
    cmds:
      - ./misc/root mkdir /jellyfin
      - ./misc/root chown -R jellyfin:jellyfin /jellyfin
  server:
    cmds:
      - ssh glenda@100.72.219.114 "cd ~/.dotfiles;git pull; echo 'CONF=server' > misc/.env; task apply"
