---
version: '3'

dotenv: ['misc/.env']

tasks:
  apply:
    cmds: 
      - task: hostid
      - echo "applying $CONF ..."
      - ./misc/root nixos-rebuild --flake .#$CONF -p $CONF switch
      - task: rm-hostid

  vm:
    cmds: 
      - task: hostid
      - echo "building VM of $CONF ..."
      - ./misc/root nixos-rebuild --flake .#$CONF -p $CONF build-vm
      - task: rm-hostid

  hostid:
    cmds:
      - sed -i "s/12355671/$(head -c 8 /etc/machine-id)/g" system/configuration.nix

  rm-hostid:
    cmds:
      - sed -i "s/$(head -c 8 /etc/machine-id)/12355671/g" system/configuration.nix

  cp-hardware:
    cmds:
      - cp -f /etc/nixos/hardware-configuration.nix system

  auto-snapshot:
    cmds:
      - ./misc/root zfs set com.sun:auto-snapshot=true NIXROOT/home

  update:
    cmds:
      - nix flake update
  
  cupdate:
    cmds:
      - task: update
      - git add flake.lock
      - git commit -m "update flake.lock"

  test:
    cmds:
      - task: apply
      - nix flake check

  push:
    cmds:
      - task: test
      - git push


  apply-user:
    cmds:
      - nix build .#homeManagerConfigurations.$USER.activationPackage
      - ./result/activate
