#!/bin/sh
# Taskfile but no misc/* dependencies
# This does not inclue full support for nixops and server deployment.
log_level=${log_level:-1}

log() {
   # Usage: log message log_level
   # Example: log "hello" 1
   if [ "$log_level" -ge "$2" ]
   then
      if [ "$2" -eq 1 ]
      then
         printf '\033[1m >> %s \n\033[m' "$1" 
      else
         printf '%s \n' "$1"
      fi
   fi
}

fatal() {
   # Usage: fatal message
   printf '\033[1m [erorr] %s \n\033[m' "$1" 
   exit 1
}

load_task_file() {
   if [ -s Taskfile.sh ]; then
      . Taskfile.sh
   else
      fatal "no Taskfile.sh found"
   fi
}

run_task() { 
   # a function which reads this file and looks for functions with "# task" behind them/
   # If "$1" is equal to the name of a function it executes this function
   # all without any dependencies
   # Usage: run_task "$1"
   load_task_file
   keyword="() { # task"
   while IFS= read -r line || [ -n "$line" ]; do # read file line for line
      case $line in # grep for *"keyword" without using grep
         *"$keyword")
            task_name="${line%%"$keyword"}"
            if [ "$1" = "list" ]; then
               printf '%s\n' "$task_name"
            else
               if [ "$1" = "$task_name" ]; then
                  log "$task_name" 1
                  $task_name
               fi
            fi
      ;;
      *)
      ;;
esac
   done < "Taskfile.sh"
}

run_task "$1"
